pypi_name = "astrbot_canary"
group = "core"
name = "last_loaded_modules"
description = "List of modules loaded in the last session"

[value]
loader = [ [ "astrbot.modules.loader", "canary_loader",],]
web = [ [ "astrbot.modules.web", "canary_web",],]
tui = [ [ "astrbot.modules.tui", "canary_tui",],]
unknown = [ [ "", "",],]

[default]
loader = [ [ "astrbot.modules.loader", "canary_loader",],]
web = [ [ "astrbot.modules.web", "canary_web",],]
tui = [ [ "astrbot.modules.tui", "canary_tui",],]
unknown = [ [ "", "",],]

[value.last_loaded_modules]
astrbot_canary_loader = [ "loader", "astrbot.modules.loader", "canary_loader",]

[default.last_loaded_modules]
