name = "boot"
group = "core"
description = "核心模块配置项"

[value]
modules = [ "canary_core", "canary_loader", "canary_web", "canary_tui",]
boot = [ "canary_core", "canary_loader", "canary_web",]

[default]
modules = [ "canary_core", "canary_loader", "canary_web", "canary_tui",]
boot = [ "canary_core", "canary_loader", "canary_web",]
