name = "boot"
group = "core"
description = "核心模块配置项"

[value]
modules = [ "astrbot_canary_core", "astrbot_canary_loader", "astrbot_canary_web", "astrbot_canary_tui",]
boot = [ "astrbot_canary_core", "astrbot_canary_loader", "astrbot_canary_web",]

[default]
modules = [ "astrbot_canary_core", "astrbot_canary_loader", "astrbot_canary_web", "astrbot_canary_tui",]
boot = [ "astrbot_canary_core", "astrbot_canary_loader", "astrbot_canary_web",]
