pypi_name = "astrbot_canary"
group = "core"
name = "worker"
description = "config of worker threads for taskiq"

[value]
count = 2
log_level = "INFO"
modules = []
tasks_pattern = [ "**/tasks.py",]
fs_discover = false
configure_logging = true
log_format = "[%(asctime)s][%(name)s][%(levelname)-7s][%(processName)s] %(message)s"
no_parse = false
shutdown_timeout = 5.0
reload = false
reload_dirs = []
no_gitignore = false
max_async_tasks = 100
receiver = "taskiq.receiver:Receiver"
receiver_arg = []
max_prefetch = 0
no_propagate_errors = false
max_fails = -1
ack_type = "when_saved"
hardkill_count = 3
use_process_pool = false

[default]
count = 2
log_level = "INFO"
modules = []
tasks_pattern = [ "**/tasks.py",]
fs_discover = false
configure_logging = true
log_format = "[%(asctime)s][%(name)s][%(levelname)-7s][%(processName)s] %(message)s"
no_parse = false
shutdown_timeout = 5.0
reload = false
reload_dirs = []
no_gitignore = false
max_async_tasks = 100
receiver = "taskiq.receiver:Receiver"
receiver_arg = []
max_prefetch = 0
no_propagate_errors = false
max_fails = -1
ack_type = "when_saved"
hardkill_count = 3
use_process_pool = false
