repos:
- hooks:
  - exclude: ^(test/|examples/)
    id: check-ast
  - exclude: ^(test/|examples/)
    id: trailing-whitespace
  - id: check-toml
  - exclude: ^(test/|examples/)
    id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - args:
    - --fix
    - --exit-non-zero-on-fix
    exclude: ^(test/|examples/)
    id: ruff-check
    types_or:
    - python
    - pyi
  - exclude: ^(test/|examples/)
    id: ruff-format
    types_or:
    - python
    - pyi
  repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.14.1
- hooks:
  - additional_dependencies:
    - types-toml
    args:
    - --config-file=pyproject.toml
    - --exclude=.*\.pyi$
    exclude: ^(test/|examples/)
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
