repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        exclude: ^(test/|examples/)
      - id: trailing-whitespace
        exclude: ^(test/|examples/)
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^(test/|examples/)
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args:
          - --fix
          - --exit-non-zero-on-fix
        exclude: ^(test/|examples/scripts|__about__.py)
        types_or:
          - python
          - pyi
      - id: ruff-format
        exclude: ^(test/|examples/scripts|__about__.py)
        types_or:
          - python
          - pyi

  - repo: local
    hooks:
      - id: mypy-allow-fail-cmd
        name: mypy (allow failure - cmd)
        language: python
        entry: cmd /c "python -m mypy --config-file=pyproject.toml --exclude=.*\.pyi$ %* || exit /b 0"
        pass_filenames: true
        files: \.py$
        stages: [commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
