[project]
name = "astrbot-canary"
version = "0.1.1"
description = "This is an official support Astrbot."
readme = "README.md"
authors = [
    { name = "LIghtJUNction", email = "LIghtJUNction.me@gmail.com" }
]
requires-python = ">=3.13.8"
dependencies = [
    "astrbot-canary-api",
    "astrbot-canary-loader",
    "astrbot-canary-loader-api",
    "astrbot-canary-web",
    "asyncio>=4.0.0",
    "click>=8.3.0",
    "dotenv>=0.9.9",
    "kombu>=5.5.4",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.11.0",
    "rich>=14.1.0",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/astrbot_canary",
    "astrbot_canary_modules/astrbot_canary_loader",
    "astrbot_canary_modules/astrbot_canary_loader_api",
    "astrbot_canary_modules/astrbot_canary_api",
    "astrbot_canary_modules/astrbot_canary_web",
    "astrbot_canary_modules/astrbot_canary_tui"
]

[tool.uv.workspace]
members = [
    "astrbot_modules/astrbot_canary_web",
    "astrbot_modules/astrbot_canary_loader",
    "astrbot_modules/astrbot_canary_loader_api",
    "astrbot_modules/astrbot_canary_api",
    "astrbot_modules/astrbot_canary_tui",
]

[tool.uv.sources]
astrbot-canary-api = { workspace = true }
astrbot-canary-web = { workspace = true }
astrbot-canary-loader = { workspace = true }
astrbot-canary-loader-api = { workspace = true }

# 后续将上述组件改为可选依赖


# [tool.uv.sources]
# orjson = { git = "https://github.com/ijl/orjson.git" ,tag = "3.11.0"}
# pyo3最新支持到3.13
# 等后续pyo3支持到14后直接升级到14

# 对于插件项目：
# [project.entry-points."astrbot.plugins"]
# "example-plugin" = "examples.plugin_example:Plugin"      # 指向插件类

# # 插件可以通过寻找这些入口点来调用核心功能，并可以依据需要混合使用不同版本的实现
# [project.entry-points."astrbot.modules.core"]



