[project]
name = "astrbot-injector"
<<<<<<< Updated upstream
version = "0.1.3"
description = "Astrbot Dependencies injector"
=======
version = "0.1.2"
description = "基于wrapt的依赖注入库."
>>>>>>> Stashed changes
readme = "README.md"
authors = [
    { name = "LIghtJUNction", email = "LIghtJUNction.me@gmail.com" }
]
requires-python = ">=3.13.8"
dependencies = [
<<<<<<< Updated upstream
    "fastapi>=0.120.0",
    "wrapt>=2.0",
]

=======
    "wrapt>=1.17.3",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-cov>=4.0",
    "coverage>=7.0",
]

[project.urls]
Homepage = "https://github.com/lightjunction/astrbotcanary"
Source = "https://github.com/lightjunction/astrbotcanary"

>>>>>>> Stashed changes
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

<<<<<<< Updated upstream
=======
[tool.hatch.build.targets.wheel]
packages = ["src/astrbot_injector"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
]
>>>>>>> Stashed changes
