pypi_name = "astrbot_canary_web"
group = "basic"
name = "common"
description = "Web UI 监听的主机地址"

[value]
host = "127.0.0.1"
port = 8080
webroot = ".astrbot\\webroot"

[default]
host = "127.0.0.1"
port = 8080
webroot = ".astrbot\\webroot"
