name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Create and activate uv virtualenv
        run: |
          uv venv .venv
          source .venv/bin/activate
      - name: Install dependencies with uv
        run: |
          uv pip install -e .[dev]
          uv pip install pytest coverage codecov
      - name: Run tests with coverage (uv)
        run: |
          uv coverage run -m pytest
          uv coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml